In [1]:
# Import Libraries 
import pandas as pd
import numpy as np

In [31]:
# Import Dataset
Date=pd.read_csv('orders.csv')
Date.head(3)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1

In [32]:
# Show the data type of date column
Date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [33]:
# Import Dataset
Time=pd.read_csv('messages.csv')
Time.head(3)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00          Днепр.м 43 позн.с д/ж *.о  067.16.34.576

In [34]:
# Show the data type of date column
Time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [35]:
                # ------Working with Dates-------#
# Convert the datatype of date column
Date['date']=pd.to_datetime(Date['date'])
Date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [36]:
# Extract Year
Date['date_year']=Date['date'].dt.year
Date.head(3)

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018

In [37]:
# Extract Month
Date['date_month_no']=Date['date'].dt.month
Date.head(3)

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10

In [38]:
#Extract Month Name
Date['date_month_name']=Date['date'].dt.month_name()
Date.head(3)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October

In [ ]:
# Extract Day
Date['date_day']=Date['date'].dt.day
Date.head(3)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23

In [ ]:
# Extract Week
Date['date_week']=Date['date'].dt.dayofweek
Date.head(3)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1

In [40]:
# Extract Day NAme
Date['date_DayName']=Date['date'].dt.day_name()
Date.head(3)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_DayName
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday

In [42]:
# Convert Date column of Time dataset
Time['date']=pd.to_datetime(Time['date'])
Time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
# Extract hour
Time['hour']=Time['date'].dt.hour

In [ ]:
# Extract min 
Time['min']=Time['date'].dt.minute

In [48]:
# Extract sec
Time['sec']=Time['date'].dt.second

In [49]:
# Check the dataset
Time.head(3)

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0

In [50]:
# Extract time
Time['time']=Time['date'].dt.time

In [51]:
Time

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00
...,...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0,00:50:00
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0,23:14:00
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0,23:37:00
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0,23:34:00
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0,23:25:00